[phases.setup]
aptPkgs = [
  "libnss3t64",
  "libatk1.0-0t64",
  "libatk-bridge2.0-0t64",
  "libcups2t64",
  "libdbus-1-3t64",
  "libdrm2",
  "libxkbcommon0-t64",
  "libxcomposite1",
  "libxdamage1",
  "libxfixes3",
  "libxrandr2",
  "libgbm1",
  "libxshmfence1",
  "libasound2t64",
  "fonts-liberation",
  "libgobject-2.0-0t64"
]
